---
title: "Tutorial Guide for Stats II Wk 1"
author: "Martyn Egan"
date: "2023-01-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(stargazer)
```

## Learning Outcomes

Today's tutorial is a refresher of the R skills we learnt in the first semester.

1. Importing data
2. Wrangling data
3. Analysing data
4. Communicating results

We will attempt to do all of this in 1 hour!

## Case study

A fictional think-tank, the Alliance of Wealthy People who Dislike Tax, has asked you to study the relationship between tax, regulation and GDP per capita. They believe that countries with low tax and light regulation are wealthier, and they want you to prove it using statistics!

## Creating the dataset

For this task, we need data. The World Bank has the information we need.

1. Go to https://databank.worldbank.org/source/world-development-indicators
2. In the `add country` screen, select the region `Europe and Central Asia`, then click `select all`. Close the pop-up.
3. In the `add series` screen, select `Ease of Doing Business Rank`, `GDP per capita (current US$)` and `tax revenue (% of GDP)`. Tip: you can use the letters to skip to the right section. Close the pop-up.
4. In the `add time` screen, select the year 2019.
5. Click `apply changes`.
6. On the left side of the screen, click the `layout` option.
7. Change `country` to `row`. Click `apply changes`.
8. Change `series` to `column`. Click `apply changes`.
9. Change `time` to `page`. Click `apply changes`.
10. In `download options` in the top right, choose `CSV`. Save to desktop.
11. Open the folder on the desktop, click `extract all`. Extract to the `data` folder.

Well done, you've got your dataset! Now let's work with the data in R. Create a new R script and save it in the `code` folder.

## Importing the data

Your csv file should now be in the data folder. We'll use some built-in functionality of RStudio to help us. 

1. In the `files` window in the bottom right, click the `...` box and open the `data` folder. 
2. Open the data file we just imported using `import dataset...`. 
3. In the window that opens, you'll notice we can manually change the type of data for each column...

## Wrangling the data

We should now have a dataset where our variables are at least of the correct type. However, we need to do a bit of tidying to get the data into a more user-friendly format. 
  
1. First, take a look at the data. Use the functions we learned from last term. 
2. If you haven't already done so when importing, drop any rows and columns we don't need. 
3. Let's also get rid of the variable code in square brackets. Try building a regular expression using the function `sub()` with the regexp `\\[.*`
  
## Analysing the data

Now that we have a dataset in the desired format, we can proceed to the analysis.

1. Let's perform some preliminary descriptive analysis using our visualisation skills. Try using ggplot to create a plot of scatter showing `GDP p/c` vs `Tax revenue`. Add a simple linear regression line.
2. Now let's try the same using `GDP p/c` vs `Ease of Doing Business`.
3. And, for the sake of argument, let's see what the relationship is between `Tax` and `Ease of Doing Business`.
4. Let's think for a minute before we perform the multivariate regression: what kind of interaction are we seeing with these three plots?
5. Now let's run a regression!

How do we interpret the results?

## Communicating

The final task is to communicate our results. We're going to do this in pdf format using latex, and then upload our results to github, just as we would with a problem set!

### Visualisation 

We want a good visualisation of our results, including a title. We've seen that `Ease of Doing Business` doesn't seem to have a very significant effect (statistically or substantively), so let's plot `GDP` vs `Tax`, and include `Ease of Doing Business` as either a size or alpha variable to our scatter points. 

1. Use the `export` option in the plots window to create a pdf of the plot.
2. Save it in the `results` folder, where you will also find your latex template.

### Regression table

We'll use stargazer to create the latex code for our regression table. 

1. Clear your console, then run stargazer on the model. Remember to add the correct `type =` argument.
2. Update the latex template, adding the table and the visualisation.
3. Compile the template and upload the pdf to github!